version: "3.9"
services:
  fastapi_template:
    image: fastapi_template
    # restart: always
    environment:
      docker: "true"
      TZ: "Europe/Istanbul"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3654:3654"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]