version: "3.9"
services:
  fastapi_template:
    image: fastapi_template
    # restart: always
    environment:
      docker: "true"
      TZ: "Europe/Istanbul"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3654:3654"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
  celery:
    image: celery
    environment:
      docker: "true"
    build:
      context: .
      dockerfile: services/celery/Dockerfile
  flower:
    image: celery
    command:
      [
        "celery",
        "-A",
        "services.celery.email.service",
        "flower",
        "--address=0.0.0.0",
        "--port=5555"
      ]
    ports:
      - "5555:5555"